### PR TITLE
Swipl-Wasm Dockerfile

### PR DESCRIPTION
**Pull request by jacobfriedman**
More to come (exposing server... and serving the compiled browser-WASM instance)

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Oops, had forgotten about this PR.  Merged.  Thanks!

**Comment by rla** [comment]
@JanWielemaker, unforunatelly these instructions cannot be used for building SWI wasm. They are in the wrong order. For example, zlib is built for the native arch before emsdk is activated. This will cause issues in the later stages of the build.

@jacobfriedman, please submit another PR and make sure it actually creates the wasm binary at the end.

Sorry for notifying so late. I tested this PR on my computer, found the issues but forgot to document them here. There have been lots of people asking for the wasm build and the older, now defunct instructions make things very confusing for them.

**Comment by JanWielemaker** [comment]
Of course I should have tested :cry:   I accepted because in any case it is good to start this and it cannot do much harm.    Docker is quite nice to setup (cross) compiling environments!

**Comment by rla** [comment]
I'm working on this. The base dockerfile is here, although the build order is still wrong:
<https://github.com/jacobfriedman/swipl-wasm/blob/master/docker/Dockerfile>

Also linking to issue <https://github.com/SWI-Prolog/swipl-devel/issues/690>
I will close that issue if the build without the flag works.

**Pull request merged**
